# Change these first
owner: getfetch-io # Your GitHub username
repo: status.getfetch.io # Your Github repository name

# Add your sites here
sites:
  - name: Landing Page
    url: https://getfetch.io
  - name: App
    url: https://app.getfetch.io
  - name: API
    url: https://api.getfetch.io
    expectedStatusCodes:
      - 200
      - 404
  - name: Blog
    url: https://blog.getfetch.io
  - name: App (staging)
    url: https://staging.getfetch.io
  - name: API (staging)
    url: https://dev.getfetch.io

status-website:
  cname: status.getfetch.io
  logoUrl: https://avatars2.githubusercontent.com/u/70174612?s=400&u=ad5d7c8bcab493c5eb950742d3409516493e722b&v=4
  name: Fetch
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
notifications:
  - type: slack
    channel: C016QTUHP9A
